//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int STT { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> soluong { get; set; }
        public string ghichu { get; set; }
        public string DICHI { get; set; }
        public string chiphi { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    }
}
